on: pull_request
env:
  TESTING_OCI_ARTIFICAT_TAG: "/pr-${{ github.event.pull_request.number }}"
  COMMIT_SHA: "${{ github.event.pull_request.head.sha }}"

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/nice.js')
            await script({github, context, core})

