on: pull_request

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set enviroment
        shell: bash
        run: |
          git show-ref --head
          echo "sha_short=$(git rev-parse HEAD)" >> "$GITHUB_ENV"
      - uses: actions/github-script@v7
        env:
          SHA: ${{ env.sha_short }}
        with:
          script: |
            const {SHA} = process.env;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `**Welcome**, new contributor!
            you can now use this "${SHA}" for ghcr images
            Please make sure you've read our [contributing guide](CONTRIBUTING.md) and we look forward to reviewing your Pull request shortly ✨`
            });
