on: pull_request
env:
  TESTING_OCI_ARTIFICAT_TAG: "/pr-${{ github.event.pull_request.number }}"
  COMMIT_SHA: "${{ github.event.pull_request.head.sha }}"

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const {TESTING_OCI_ARTIFICAT_TAG,COMMIT_SHA} = process.env;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Steps on How to run testing
            
            > [!NOTE]
            > Given below steps help you to run the e2e tests on the PRs latest changes
            > using the latest built images.

            > [!WARNING]
            > These images are built for testing purposes only and should not be used in production.

            \`\`\`shell
            # first need to generate the application controller installer
            # make sure you don't push it to the PR
            make build-installer CONTROLLER="application" CUSTOM_LOCATION_GEN_CONTROLLER_MANIFEST="/tmp/ksctl-manifest.yaml" IMG_SUFFIX="${TESTING_OCI_ARTIFICAT_TAG}" IMG_TAG_VERSION="${COMMIT_SHA}"
            
            cd test/e2e
            go build -v -ldflags="-X 'github.com/ksctl/ksctl/commons.OCIVersion=${COMMIT_SHA}' -X 'github.com/ksctl/ksctl/commons.OciImgSuffix=${TESTING_OCI_ARTIFICAT_TAG}'" .
            ./e2e -op create -file local/create.json
            ./e2e -op switch -file local/switch.json
            ./e2e -op delete -file local/delete.json
            \`\`\`
            Please make sure you've read our [contributing guide](CONTRIBUTING.md) and we look forward to reviewing your Pull request shortly ✨`
            })


